/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 Draco.gltf --transform 
Files: Draco.gltf [19.6MB] > Draco-transformed.glb [1.1MB] (94%)
Author: Urpo (https://sketchfab.com/Urpo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-f844c0357d284fd8baa1435e9ff31bb2
Title: Retro computer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Part2} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Part1} />
    </group>
  )
}

useGLTF.preload('/Draco-transformed.glb')
